timeout: 1

/EquantOS (Live Installer)
    protocol: limine
    kernel_path: boot():/boot/kernel.elf
    module_path: boot():/boot/kernel.elf
    module_path: boot():/limine.conf
    module_path: boot():/boot/limine-bios.sys
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_path: boot():/font.psf
    module_path: boot():/bash.elf
    module_path: boot():/busybox.elf
    module_path: boot():/.bashrc
    module_path: boot():/hello.elf