timeout: 1

/EquantOS
    protocol: limine
    kernel_path: boot():/boot/kernel.elf
    module_path: boot():/font.psf
    module_path: boot():/hello.elf
    module_path: boot():/musltest.elf
    module_path: boot():/busybox.elf
    module_path: boot():/equantmemtest.elf
    module_path: boot():/bash.elf
    module_path: boot():/.bashrc